'use client';
import { X, TrendingUp, DollarSign, PieChart as PieChartIcon, FileText, Download, Users, Clock, IndianRupee } from 'lucide-react';
import { BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import { useState } from 'react';

interface ClientReportsProps {
  clientName: string;
  onClose: () => void;
}

type ReportType = 'hourlyRate' | 'profitability' | 'revenue';

export function ClientReports({ clientName, onClose }: ClientReportsProps) {
  const [selectedReport, setSelectedReport] = useState<ReportType>('hourlyRate');

  // Sample data for different resources - replace with actual data
  const resourceData = [
    {
      name: 'Resource 1',
      hodSrManager: 797,
      manager: 379,
      srExecutive: 364,
      jrExecutive: null,
      graphicsManager: null,
      graphicsExecutive: null,
      linkedinWhatsapp: null,
    },
    {
      name: 'Resource 2',
      hodSrManager: 797,
      manager: 328,
      srExecutive: 328,
      jrExecutive: null,
      graphicsManager: null,
      graphicsExecutive: null,
      linkedinWhatsapp: null,
    },
    {
      name: 'Resource 3',
      hodSrManager: 797,
      manager: 379,
      srExecutive: null,
      jrExecutive: null,
      graphicsManager: null,
      graphicsExecutive: null,
      linkedinWhatsapp: null,
    },
    {
      name: 'Resource 4',
      hodSrManager: 797,
      manager: 253,
      srExecutive: 253,
      jrExecutive: null,
      graphicsManager: null,
      graphicsExecutive: null,
      linkedinWhatsapp: null,
    },
    {
      name: 'Resource 5',
      hodSrManager: 797,
      manager: 328,
      srExecutive: 328,
      jrExecutive: null,
      graphicsManager: null,
      graphicsExecutive: null,
      linkedinWhatsapp: null,
    },
  ];

  // Profitability data
  const profitabilityData = [
    {
      name: 'Resource 1',
      hodSrManager: 296,
      manager: 193,
      srExecutive: 1137,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 0,
    },
  ];

  // Revenue allocation data
  const revenueData = [
    {
      name: 'Period 1',
      hodSrManager: 1054,
      manager: 950,
      srExecutive: 4046,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 103,
    },
    {
      name: 'Period 2',
      hodSrManager: 0,
      manager: 0,
      srExecutive: 0,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 0,
    },
    {
      name: 'Period 3',
      hodSrManager: 9700,
      manager: 9101,
      srExecutive: 0,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 599,
    },
    {
      name: 'Period 4',
      hodSrManager: 2611,
      manager: 2401,
      srExecutive: 20889,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 211,
    },
    {
      name: 'Period 5',
      hodSrManager: 2935,
      manager: 2873,
      srExecutive: 17609,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 62,
    },
  ];

  const getCurrentData = () => {
    switch (selectedReport) {
      case 'hourlyRate':
        return resourceData;
      case 'profitability':
        return profitabilityData;
      case 'revenue':
        return revenueData;
      default:
        return resourceData;
    }
  };

  const getReportInfo = () => {
    switch (selectedReport) {
      case 'hourlyRate':
        return {
          title: 'Hourly Resource Rate',
          description: 'Cost per hour for each resource role working on this client',
          icon: Clock,
          color: 'from-[#E85D4D] to-[#F87171]',
        };
      case 'profitability':
        return {
          title: 'Resource Profitability',
          description: 'Profit margin generated by each resource role',
          icon: TrendingUp,
          color: 'from-[#10B981] to-[#34D399]',
        };
      case 'revenue':
        return {
          title: 'Revenue Allocation',
          description: 'Revenue distributed across different resource roles',
          icon: IndianRupee,
          color: 'from-[#204CC7] to-[#4D73D9]',
        };
    }
  };

  const formatCurrency = (value: number | null) => {
    if (value === null || value === 0) return '-';
    return `₹${value.toLocaleString('en-IN')}`;
  };

  const reportInfo = getReportInfo();
  const IconComponent = reportInfo.icon;
  const currentData = getCurrentData();

  // Calculate chart data
  const getChartData = () => {
    const totals = {
      hodSrManager: 0,
      manager: 0,
      srExecutive: 0,
      jrExecutive: 0,
      graphicsManager: 0,
      graphicsExecutive: 0,
      linkedinWhatsapp: 0,
    };

    currentData.forEach(row => {
      totals.hodSrManager += row.hodSrManager || 0;
      totals.manager += row.manager || 0;
      totals.srExecutive += row.srExecutive || 0;
      totals.jrExecutive += row.jrExecutive || 0;
      totals.graphicsManager += row.graphicsManager || 0;
      totals.graphicsExecutive += row.graphicsExecutive || 0;
      totals.linkedinWhatsapp += row.linkedinWhatsapp || 0;
    });

    return [
      { role: 'HOD/Sr. Manager', value: totals.hodSrManager },
      { role: 'Manager', value: totals.manager },
      { role: 'Sr. Executive', value: totals.srExecutive },
      { role: 'Jr. Executive', value: totals.jrExecutive },
      { role: 'Graphics Manager', value: totals.graphicsManager },
      { role: 'Graphics Executive', value: totals.graphicsExecutive },
      { role: 'LinkedIn/WhatsApp', value: totals.linkedinWhatsapp },
    ].filter(item => item.value > 0);
  };

  const chartData = getChartData();
  const COLORS = ['#204CC7', '#4D73D9', '#7A99E6', '#9FB8ED', '#10B981', '#F59E0B', '#E85D4D'];

  return (
    <div className="fixed inset-0 z-[60] overflow-hidden">
      <div className="absolute inset-0 bg-[#272727]/50 backdrop-blur-sm" onClick={onClose} />
      <div className="absolute inset-4 bg-gradient-to-br from-[#FAFBFF] to-[#F6F7FF] rounded-xl shadow-2xl overflow-hidden">
        <div className="h-full flex flex-col">
          {/* Header */}
          <div className={`bg-gradient-to-r ${reportInfo.color} p-6`}>
            <div className="flex items-center justify-between mb-4">
              <div>
                <h2 className="text-white text-h1">Resource Utilization Report</h2>
                <p className="text-white/80 text-body">{clientName}</p>
              </div>
              <div className="flex items-center gap-3">
                <button className="flex items-center gap-2 px-4 py-2 bg-white/20 text-white rounded-lg hover:bg-white/30 transition-all">
                  <Download className="w-4 h-4" />
                  <span>Export</span>
                </button>
                <button
                  onClick={onClose}
                  className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center hover:bg-white/30 transition-all"
                >
                  <X className="w-5 h-5 text-white" />
                </button>
              </div>
            </div>
            
            {/* Report Type Selector */}
            <div className="flex items-center gap-3 bg-white/10 backdrop-blur-sm rounded-lg p-1">
              <button
                onClick={() => setSelectedReport('hourlyRate')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-all ${
                  selectedReport === 'hourlyRate'
                    ? 'bg-white text-[#204CC7] shadow-lg'
                    : 'text-white hover:bg-white/10'
                }`}
              >
                <Clock className="w-4 h-4" />
                <span className="text-body">Hourly Rate</span>
              </button>
              <button
                onClick={() => setSelectedReport('profitability')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-all ${
                  selectedReport === 'profitability'
                    ? 'bg-white text-[#10B981] shadow-lg'
                    : 'text-white hover:bg-white/10'
                }`}
              >
                <TrendingUp className="w-4 h-4" />
                <span className="text-body">Profitability</span>
              </button>
              <button
                onClick={() => setSelectedReport('revenue')}
                className={`flex-1 flex items-center justify-center gap-2 px-4 py-3 rounded-lg transition-all ${
                  selectedReport === 'revenue'
                    ? 'bg-white text-[#204CC7] shadow-lg'
                    : 'text-white hover:bg-white/10'
                }`}
              >
                <IndianRupee className="w-4 h-4" />
                <span className="text-body">Revenue Allocation</span>
              </button>
            </div>
          </div>

          {/* Content */}
          <div className="flex-1 overflow-y-auto p-6 space-y-6">
            {/* Report Info Card */}
            <div className={`bg-gradient-to-r ${reportInfo.color} rounded-xl p-4`}>
              <div className="flex items-center gap-3 text-white">
                <div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center">
                  <IconComponent className="w-5 h-5" />
                </div>
                <div>
                  <h3 className="text-white text-h2">{reportInfo.title}</h3>
                  <p className="text-white/80 text-body">{reportInfo.description}</p>
                </div>
              </div>
            </div>

            {/* Data Table */}
            <div className="bg-white rounded-xl shadow-sm border border-[#204CC7]/10 overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="bg-gradient-to-r from-[#272727] to-[#3a3a3a]">
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">{selectedReport === 'revenue' ? 'Period' : 'Resource'}</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">HOD/Sr. Manager</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">Manager</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">Sr. Executive</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">Jr. Executive</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">Graphics Manager</th>
                      <th className="px-4 py-3 text-left text-white text-body border-r border-white/10">Graphics Executive</th>
                      <th className="px-4 py-3 text-left text-white text-body">LinkedIn/WhatsApp</th>
                    </tr>
                  </thead>
                  <tbody>
                    {currentData.map((row, index) => (
                      <tr key={index} className={index % 2 === 0 ? 'bg-white hover:bg-[#F6F7FF]' : 'bg-[#F6F7FF]/50 hover:bg-[#F6F7FF]'}>
                        <td className="px-4 py-3 text-[#272727] border-r border-[#204CC7]/10 text-body">
                          {row.name}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.hodSrManager)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.manager)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.srExecutive)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.jrExecutive)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.graphicsManager)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body border-r border-[#204CC7]/10">
                          {formatCurrency(row.graphicsExecutive)}
                        </td>
                        <td className="px-4 py-3 text-[#272727] text-body">
                          {formatCurrency(row.linkedinWhatsapp)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Visualizations */}
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              {/* Bar Chart */}
              <div className="bg-white rounded-xl shadow-sm border border-[#204CC7]/10 p-6">
                <h4 className="text-[#272727] mb-4">Distribution by Role</h4>
                <ResponsiveContainer width="100%" height={300}>
                  <BarChart data={chartData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#204CC7" strokeOpacity={0.1} />
                    <XAxis 
                      dataKey="role" 
                      angle={-15} 
                      textAnchor="end" 
                      height={100} 
                      stroke="#5A5A6F"
                      tick={{ fontSize: 12 }}
                    />
                    <YAxis stroke="#5A5A6F" />
                    <Tooltip 
                      formatter={(value) => formatCurrency(Number(value))}
                      contentStyle={{ backgroundColor: '#fff', border: '1px solid #204CC7', borderRadius: '8px' }}
                    />
                    <Bar dataKey="value" radius={[8, 8, 0, 0]}>
                      {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>

              {/* Pie Chart */}
              <div className="bg-white rounded-xl shadow-sm border border-[#204CC7]/10 p-6">
                <h4 className="text-[#272727] mb-4">Percentage Breakdown</h4>
                <ResponsiveContainer width="100%" height={300}>
                  <PieChart>
                    <Pie
                      data={chartData}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={({ percent }) => `${(percent * 100).toFixed(0)}%`}
                      outerRadius={100}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {chartData.map((entry, index) => (
                        <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                      ))}
                    </Pie>
                    <Tooltip 
                      formatter={(value) => formatCurrency(Number(value))}
                      contentStyle={{ backgroundColor: '#fff', border: '1px solid #204CC7', borderRadius: '8px' }}
                    />
                    <Legend 
                      verticalAlign="bottom" 
                      height={36}
                      formatter={(value, entry: any) => {
                        const item = chartData.find(d => d.role === entry.payload.role);
                        return item ? item.role : value;
                      }}
                    />
                  </PieChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Summary Cards */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className={`bg-gradient-to-br ${reportInfo.color} rounded-lg p-4`}>
                <div className="flex items-center gap-3 text-white">
                  <div className="w-10 h-10 bg-white/20 rounded-lg flex items-center justify-center">
                    <IconComponent className="w-5 h-5" />
                  </div>
                  <div>
                    <p className="text-white/80 text-caption">Total Value</p>
                    <p className="text-white text-h2">
                      {formatCurrency(chartData.reduce((sum, d) => sum + d.value, 0))}
                    </p>
                  </div>
                </div>
              </div>
              
              <div className="bg-white rounded-lg p-4 border border-[#204CC7]/10">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-[#204CC7] to-[#4D73D9] rounded-lg flex items-center justify-center">
                    <Users className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <p className="text-[#5A5A6F] text-caption">Active Roles</p>
                    <p className="text-[#272727] text-h2">{chartData.length}</p>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-lg p-4 border border-[#204CC7]/10">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-[#10B981] to-[#34D399] rounded-lg flex items-center justify-center">
                    <TrendingUp className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <p className="text-[#5A5A6F] text-caption">Highest Value</p>
                    <p className="text-[#272727] text-h2">
                      {formatCurrency(Math.max(...chartData.map(d => d.value)))}
                    </p>
                  </div>
                </div>
              </div>

              <div className="bg-white rounded-lg p-4 border border-[#204CC7]/10">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 bg-gradient-to-br from-[#F59E0B] to-[#FBBF24] rounded-lg flex items-center justify-center">
                    <DollarSign className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <p className="text-[#5A5A6F] text-caption">Average</p>
                    <p className="text-[#272727] text-h2">
                      {formatCurrency(Math.round(chartData.reduce((sum, d) => sum + d.value, 0) / chartData.length))}
                    </p>
                  </div>
                </div>
              </div>
            </div>

            {/* Info Note */}
            <div className="bg-[#F6F7FF] rounded-lg p-4 border border-[#204CC7]/10">
              <div className="flex items-start gap-3">
                <FileText className="w-5 h-5 text-[#204CC7] mt-0.5" />
                <div>
                  <p className="text-[#272727]">About This Report</p>
                  <p className="text-[#5A5A6F] text-body mt-1">
                    This data is automatically calculated based on team salaries and estimated effort hours assigned to this client. 
                    Update the estimated effort in the client details to see changes reflected here.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}